Secret.Key: ${JWT_Secret_Key}

---
spring:
  profiles: local
  datasource:
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379

  jpa:
    database-platform: H2
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org:
        hibernate:
          type: trace

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ture
          starttls:
            enable: true

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${MYSQL_URL}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST}
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_NAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ture
          starttls:
            enable: true
---

spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: testName
    password: testPassword
    properties:
      mail:
        smtp:
          auth: ture
          starttls:
            enable: true
Secret.Key: 반갑습니다. 이것은 테스트용 키입니다. 아주 길어야 하거든요.